### PR TITLE
README: Add a screenshot, using github markdown.

### PR DESCRIPTION
**Pull request by murraycu**

### CODE REVIEW

**Comment by murraycu** [comment]
Just so people can see how pretty it is.

I was thinking of converting this to use gtkmm-3.0 and Gtk::GLArea, but that doesn't look like much fun.

**Comment by danielkitta** [comment]
Merged, thanks. I also added a list of available keyboard shortcuts.
Yeah, porting this to gtkmm 3 probably involves a bit of grunt work. Adopting Gtk::GLArea could also turn out to be somewhat tricky.

**Comment by danielkitta** [comment]
I just had a look at Gtk::GLArea. At first porting looks relatively straight-forward, with the exception of multisample AA because GtkGLArea insists on creating its own render buffers without any obvious way to control parameters. GtkGLArea is very thin though -- porting might be even easier by just using the GdkGLContext/Gdk Cairo APIs directly.

However, then I had a look at gdk_cairo_draw_from_gl(). The documentation talks about a fast direct rendering path, but either I'm stupid or the implementation of that simply doesn't exist. The code appears to perform a pixel readout into a CPU-side memory buffer in all cases. Yikes! At this point, I'm not sure I even want to port to that, even though I like the idea of running directly on Wayland.

**Comment by danielkitta** [comment]
Just to note, a preliminary port to gtkmm3 is now in master. Gtk::GLArea is working OK, I managed to bypass all of its own buffer setup. The problems I noticed in gdk_cairo_draw_from_gl() are not in GTK+ 3, but in the new GTK+ 4 code in git which dropped the GL fast path since it is now using Vulkan to render. I will see what to do about that when the time comes.

Expect the remaining rough edges of the GTK+ 3 port to be polished soon.

**Comment by murraycu** [comment]
Well done. I'm glad that it will stay alive.

**Pull request closed without merging**
